name: build

on:
  push:
    branches:
    - main

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: GCloud auth
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: GCloud setup
        uses: google-github-actions/setup-gcloud@v0

      - name: Install yq
        run: sudo snap install yq

      - name: Set COMMIT 
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7} yq '.env_variables.COMMIT = strenv(SHORT_SHA)' --inplace ./app.yaml 

      - name: Set LASTMODIFIED
        run: |
          LASTMOD="$(date -u +%Y-%m-%dT%H:%M:%SZ)" yq '.env_variables.LASTMOD = strenv(LASTMOD)' --inplace ./app.yaml 

      - name: Deploy to AppEngine
        run: |
          gcloud app deploy --project=${{ secrets.GCP_PROJECT }} --quiet
